print("Hello semua")
print("Apa kabar")
print("Pasti sehat")
print("Semoga panjang umur")
print("Semoga di beri berkah")
print("di siang hari ini")
print("Saya akan memperkenal kan diri")
print("Nama saya rhafa fahmi s")
print("bisa di panggil Fahmi")
print("Hobi saya bermain bulutangkis sekian terima kasih")